# Configuration for the exchange and default behavior
# The name of the exchange to connect to.
# Possible values: "binance", "okx"
exchange: "okx"  # Example: "binance

# Your local time zone (does not affect data)
# See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# for a list of all possible values.
# The default is Beijing time zone +8
Zone: 8 #If the Beijing time zone is UTC+8, fill in 8

# Scheduled tasks use by default
# Possible values: false, true
cronTasks: false

# Query the interval for price changes
# Note: This option will only take effect when cronTasks is ‘false’.
# Possible values: "1m", "5m", "15m", "1h", "1d".
queryInterval: "5m"

# The default timeframe (frequency of data retrieval).
# Possible values: "1m", "5m", "15m", "1h", "1d".
defaultTimeframe: "5m"  # Example: "5m"

# The default price change threshold. Only pairs exceeding this value will be notified.
# Here 1 is equivalent to 1%
defaultThreshold: 1  # Example: 1

# The file path containing trading pair symbols. If empty, pairs will be auto-retrieved.
symbolsFilePath: "config/symbols.txt"  # Example: "config/symbols.txt"

# Notification channels and configuration
# The channels for receiving notifications. Currently supports Telegram and DingDing.
notificationChannels: 
  - "telegram"
  - "dingding"

# Telegram bot configuration
# The token used to connect to the Telegram bot.
telegram:
  token: "7820507276:AAGKpVPgc4uJ7zd4SmrpZB6geu5aU4VylFo"  # Example: "your_telegram_bot_token"

  # The Telegram chat ID where notifications will be sent.
  chatId: "-1002275845855"  # Example: "your_chat_id"

# DingDing robot configuration
# The DingDing robot webhook URL for sending notifications.
dingding:
  webhook: "https://oapi.dingtalk.com/robot/send?access_token=5b6aa267b4e3c954e995a3fc5286c540d4261b835eed754dabef2b933b4fb02a"  # Example: "https://oapi.dingtalk.com/robot/send?access_token=your_access_token"

  # The DingDing robot secret used to generate the signature for secure notifications.
  secret: "SEC91b409df60966f4d122fe142d258045e0685fc270cca92247679ae41f3e2739f"  # Example: "your_sign_secret"